# Generated by Django 4.1.2 on 2022-10-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Name', models.CharField(max_length=255)),
                ('Emp_Pwd', models.CharField(max_length=255)),
                ('Emp_Email', models.CharField(max_length=255)),
                ('Emp_Age', models.IntegerField()),
                ('Emp_Designation', models.CharField(max_length=255)),
                ('EmpAddress', models.CharField(max_length=255)),
            ],
        ),
    ]
